# Generated by Django 5.2.6 on 2026-09-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appearance',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_locale',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone_display',
            field=models.CharField(default='UTC', max_length=63),
        ),
    ]
