# Generated by Django 5.2.6 on 2026-09-13 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimezoneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UTC', max_length=63, unique=True)),
            ],
            options={
                'verbose_name': 'organization timezone config',
                'verbose_name_plural': 'organization timezone configs',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'timesheet',
                'verbose_name_plural': 'timesheets',
                'ordering': ('-week_start', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('duration_minutes', models.IntegerField()),
                ('unpaid_break_minutes', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheets.timesheet')),
            ],
            options={
                'verbose_name': 'time entry',
                'verbose_name_plural': 'time entries',
                'ordering': ('work_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TimesheetCreateIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_create_idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'timesheet create idempotency record',
                'verbose_name_plural': 'timesheet create idempotency records',
            },
        ),
        migrations.CreateModel(
            name='TimesheetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], max_length=16)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=16, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=16, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet_events', to=settings.AUTH_USER_MODEL)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timesheets.timesheet')),
            ],
            options={
                'verbose_name': 'timesheet event',
                'verbose_name_plural': 'timesheet events',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['employee'], name='idx_timesheet_employee'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('employee', 'week_start'), name='uniq_timesheet_employee_week_start'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(condition=models.Q(('week_start__week_day', 2)), name='chk_timesheet_week_start_monday'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(fields=('timesheet', 'work_date'), name='uniq_timeentry_sheet_work_date'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 0)), name='chk_timeentry_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('unpaid_break_minutes__gte', 0)), name='chk_timeentry_break_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__lte', 1440)), name='chk_timeentry_duration_within_day'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('unpaid_break_minutes__lte', 1440)), name='chk_timeentry_break_within_day'),
        ),
        migrations.AddConstraint(
            model_name='timesheetcreateidempotencyrecord',
            constraint=models.UniqueConstraint(fields=('key_hash', 'user'), name='uniq_timesheet_create_idem_key_user'),
        ),
    ]
