# Generated by Django 5.2.6 on 2026-09-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_seed_timezone_utc'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timezoneconfig',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='chk_timezone_config_singleton'),
        ),
    ]
