# Generated by Django 5.2.6 on 2026-09-13 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_timezoneconfig_chk_timezone_config_singleton'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetSubmitIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_submit_idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'timesheet submit idempotency record',
                'verbose_name_plural': 'timesheet submit idempotency records',
                'constraints': [models.UniqueConstraint(fields=('key_hash', 'user'), name='uniq_timesheet_submit_idem_key_user')],
            },
        ),
    ]
