# Generated by Django 5.2.6 on 2026-09-11 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('requires_hr_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default='', max_length=10000)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_MANAGER', 'Pending manager'), ('PENDING_HR', 'Pending HR'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('manager_at_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_to_review', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='reqs.requesttype')),
            ],
            options={
                'verbose_name': 'employee request',
                'verbose_name_plural': 'employee requests',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited')], max_length=16)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_MANAGER', 'Pending manager'), ('PENDING_HR', 'Pending HR'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], max_length=32, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_MANAGER', 'Pending manager'), ('PENDING_HR', 'Pending HR'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], max_length=32, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reqs.employeerequest')),
            ],
            options={
                'verbose_name': 'request event',
                'verbose_name_plural': 'request events',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
