# Generated by Django 5.2.6 on 2026-09-11 23:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
