# Generated by Django 5.2.6 on 2026-09-12 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0004_employeerequest_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'decision idempotency record',
                'verbose_name_plural': 'decision idempotency records',
                'constraints': [models.UniqueConstraint(fields=('key_hash', 'user'), name='uniq_decision_idem_key_user')],
            },
        ),
    ]
