# Generated by Django 5.2.6 on 2026-09-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0005_decisionidempotencyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], max_length=16),
        ),
    ]
