# Generated by Django 5.2.6 on 2026-09-12 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0006_alter_requestevent_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], max_length=16),
        ),
        migrations.CreateModel(
            name='CancelIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cancel idempotency record',
                'verbose_name_plural': 'cancel idempotency records',
                'constraints': [models.UniqueConstraint(fields=('key_hash', 'user'), name='uniq_cancel_idem_key_user')],
            },
        ),
    ]
